### ISSUE TITLE
Suggestion: Use for https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/package-detail.html

### ISSUE THREAD

**Issue by danielhjacobs** [golfinq/ActionScript_Event_Builder#7]
These are all just enum classes:

- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/BreakOpportunity.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/CFFHinting.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/DigitCase.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/DigitWidth.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/FontLookup.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/FontPosture.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/FontWeight.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/JustificationStyle.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/Kerning.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/LigatureLevel.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/LineJustification.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/RenderingMode.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TabAlignment.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextBaseline.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextLineCreationResult.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextLineValidity.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextRotation.html
- https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TypographicCase.html

**Comment by danielhjacobs** [comment]
Implemented it myself in https://github.com/ruffle-rs/ruffle/pull/9275

**Comment by golfinq** [comment]
Thank you for using it, hopefully the scripts weren't difficult to use!
